stages:
  - build-dev
  - deploy-dev

build-dev:
  stage: build-dev
  # only:
  #   - dev
  tags:
    - debian
    - dss
  script:
    - docker build -t webx-engine-builder .
    - docker rm -f webx-engine-builder || true
    - docker create -ti --name webx-engine-builder webx-engine-builder bash
    - docker cp webx-engine-builder:/app/packages/. .
    - docker rm -f webx-engine-builder
    - PACKAGE_VERSION=`awk '/CPACK_PACKAGE_VERSION /{ gsub(/[()]/, " "); gsub(/[\"]/, ""); print $3}' CMakeLists.txt`
    - cp webx-engine_${PACKAGE_VERSION}_amd64.deb webx-engine_dev_amd64.deb
  artifacts:
    paths:
      - webx-engine_dev_amd64.deb

deploy-dev:
  stage: deploy-dev
  # only:
  #   - dev
  tags:
    - debian
    - dss
  script:
    - scp webx-engine_dev_amd64.deb webx@webx-dev.ill.fr:/data/deb/
    - ssh webx@webx-dev.ill.fr "cd /data/apps/webx-deploy; git pull --rebase origin dev;"
    - ssh root@webx-dev.ill.fr "cd /data/apps/webx-deploy; ./deploy-deb.sh"